### ISSUE TITLE
file to import not found or unreadable: bootstrap

### ISSUE THREAD

**Issue by sbsurf** [lifegadget/ember-cli-bootstrap-sassy#8]
Hello,

I am having trouble using your add-on. I get the following errors when trying to build:

```
File: /Users/me/projects/blah/tmp/tree_merger-tmp_dest_dir-c9AFWRJW.tmp/app/styles/app.scss (1)
file to import not found or unreadable: bootstrap
Current dir: /Users/me/projects/blah/tmp/tree_merger-tmp_dest_dir-c9AFWRJW.tmp/app/styles/
```

app/styles/app.scss:

```
@import "bootstrap";
```

package.json:

```
...
"devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "0.2.0-beta.1",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-bootstrap-sassy": "0.0.12",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.8",
    "ember-cli-sass": "^3.1.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.15",
    "ember-export-application-global": "^1.0.2",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
```

ember-cli v. 0.2.0-beta.1
ember v. 1.10.0

**Comment by sbsurf** [comment]
Resolved issue by adding this to config/environment.js:

```
  ENV.sassOptions = {
    includePaths: [
      'bower_components/bootstrap-sass-official/assets/stylesheets'
    ]
  }
```

**Comment by yankeeinlondon** [comment]
Yes I'm afraid this is due to a breaking change in the way ember-cli v0.2.0 handles cascading dependencies (aka, bootstrap sass depends on sass). It's on my list of things to fix but I'd happily take a PR if someone has the time for that.

**Comment by vicentereig** [comment]
@ksnyde Would mind give us an overview on how to fix it?I'm willing to fix it, as I'm upgrading an ember-cli project from 0.1.3 to 0.2.0, but I'm still missing what bits have changed ever since.

**Comment by yankeeinlondon** [comment]
On the Ember CLI site they make reference to the fixes needed but when I was glancing at this the other day it occurred what I think happened may have been that the underlying ember-cli-sass addon changed and now is using ENV based configuration rather than modifying the Brocfile. Not sure about this though as it was just a passing glance.

The Ember CLI reference I was referring to is:

> In reference to `setupPreprocessorRegistry`:  [0.2.0 breaking changes](http://www.ember-cli.com/#beta1)

**Comment by yankeeinlondon** [comment]
Historically all that was needed was non-destructively adding the path to Boostrap's path into ember-cli-sass's configuration:

https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/index.js#L22

**Comment by yankeeinlondon** [comment]
would love it if you could give me a PR ... been slammed recently so haven't had any cycles but will get it merged in promptly if you have some bandwidth

**Comment by vicentereig** [comment]
@ksnyde Thanks, sounds good. I'll hit you up when I've got more questions!

**Comment by ballPointPenguin** [comment]
I did not have success with @sbsurf 's suggestion, but "solved" this by using the full path in my app.scss:

```
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
```

**Comment by yankeeinlondon** [comment]
@ballPointPenguin what version of CLI are you using? I have used @sbsurf approach without issue on 0.2.0.

**Comment by yankeeinlondon** [comment]
@vicentereig have you made any progress on that PR?

**Comment by tgandee79** [comment]
@ksnyde it looks like the sassOptions need to be in the environment config, and not in the app options.  I'll be able to test in the next two days. Working on cli version 0.2.1.

**Comment by yankeeinlondon** [comment]
@tgandee79 yup, that's a change from earlier. It happened at the same time as the API breaking change in 0.2.0 so I wasn't sure the source of the problem at first.

**Comment by tgandee79** [comment]
@ksnyde I have a working branch with a number of updates.  I can send a PR if you give me permissions.  The branch updates the node_modules to use the latest, removes hbs support in favor of htmlbars, moves the sassOptions to `treeForStyles`.  I updated the dummy app to have working bootstrap classes.

**Comment by ballPointPenguin** [comment]
@tgandee79 sounds awesome. Hope to see that soon.
@ksnyde I was using a very fresh ember-cli 0.2.1

**Comment by yankeeinlondon** [comment]
I think with all the changes that have been made this is closable. If anyone disagrees please reopen.
